# Generated by Django 5.0.4 on 2024-04-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
